spring:
  application:
    name: adminachu
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-db
    username: postgres-user
    password: postgres-password
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres-db
    user: postgres-user
    password: postgres-password
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    operations-sorter: method

logging:
  level:
    root: info
  file:
    name: adminachu.log

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, logfile
    jmx:
      exposure:
        include: "*"
  jmx:
    metrics:
      export:
        domain: metrics
        enabled: true
